version: '3.8'
services:
  finance-assistant:
    build: .
    ports:
      - "8501:8501"  # Streamlit frontend
      - "8000:8000"  # API Agent
      - "8001:8001"  # Retriever Agent
      - "8002:8002"  # Analysis Agent
      - "8003:8003"  # Language Agent
      - "8004:8004"  # Voice Agent
      - "8005:8005"  # Orchestrator
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
